import React from 'react';
import {AbsoluteFill,Audio,Img,OffthreadVideo,Sequence,interpolate,staticFile,useCurrentFrame,useVideoConfig} from 'remotion';
import type {PropertyVideoProps,VoiceSegment} from './types';

const font='Noto Sans Tamil, Noto Sans, Arial, sans-serif';
const bg='#07111c',cream='#fff8eb',gold='#ffbd2e',cyan='#5ce7ff';
const isVideo=(s:string)=>/\.(mp4|mov|m4v|webm)$/i.test(s);
const fact=(p:PropertyVideoProps,k:string,f='Verify during visit')=>p.facts.find(x=>x.label.toLowerCase().includes(k.toLowerCase()))?.value||f;
const voiceFor=(v:VoiceSegment[],s:string)=>v.find(x=>x.scene===s);
const keyFor=(s:string)=>s==='price'||s==='facing'?'exterior':s==='builtUp'?'living':s==='verify'||s==='road'?'location':s;
const inferredBg=(p:PropertyVideoProps,k:string)=>`render/${p.videoId}/layer-${k}-bg.jpg`;
const inferredFg=(p:PropertyVideoProps,k:string)=>k==='exterior'?`render/${p.videoId}/layer-exterior-fg.png`:undefined;
const sourcesFor=(p:PropertyVideoProps,s:string)=>{const k=keyFor(s);const moving=[...(p.actualVideos||[]),...(p.sceneMedia?.[k]||[]),...(p.directorMedia?.[s]||[]).map(x=>x.src)];const real=[...new Set(moving.filter(Boolean))];if(real.length)return real;const fallback=[...(p.images||[]),...(p.layerMedia?.[k]?.stills||[]),p.layerMedia?.[k]?.background||inferredBg(p,k)];return [...new Set(fallback.filter(Boolean))]};

const MovingMedia:React.FC<{src:string;frame:number;dir:number;zoom?:number}>=({src,frame,dir,zoom=1.11})=>{const x=interpolate(frame,[0,70],[-16*dir,16*dir],{extrapolateRight:'clamp'});const sc=interpolate(frame,[0,70],[1.02,zoom],{extrapolateRight:'clamp'});const st={width:'100%',height:'100%',objectFit:'cover' as const,transform:`translateX(${x}px) scale(${sc})`};return isVideo(src)?<OffthreadVideo src={staticFile(src)} muted style={st}/>:<Img src={staticFile(src)} style={st}/>};

const Kinetic:React.FC<{title:string;value?:string;note?:string}>=({title,value,note})=>{const f=useCurrentFrame();const y=interpolate(f,[0,10],[42,0],{extrapolateRight:'clamp'});const op=interpolate(f,[0,8],[0,1],{extrapolateRight:'clamp'});const sx=interpolate(f,[0,12],[.92,1],{extrapolateRight:'clamp'});return <div style={{position:'absolute',left:52,right:52,bottom:150,fontFamily:font,color:cream,opacity:op,transform:`translateY(${y}px) scale(${sx})`,zIndex:2}}><div style={{fontSize:22,fontWeight:900,letterSpacing:4,color:cyan}}>{title}</div>{value&&<div style={{fontSize:72,fontWeight:1000,lineHeight:.96,marginTop:10,textShadow:'0 10px 30px rgba(0,0,0,.6)'}}>{value}</div>}{note&&<div style={{fontSize:26,fontWeight:750,lineHeight:1.22,marginTop:15,color:'rgba(255,255,255,.82)'}}>{note}</div>}<div style={{height:7,width:interpolate(f,[2,22],[0,330],{extrapolateRight:'clamp'}),background:gold,borderRadius:9,marginTop:20}}/></div>};

const LayeredScene:React.FC<{p:PropertyVideoProps;scene:string;title:string;value?:string;note?:string}>=({p,scene,title,value,note})=>{const f=useCurrentFrame();const {fps}=useVideoConfig();const k=keyFor(scene);const l=p.layerMedia?.[k];const sources=sourcesFor(p,scene);const beat=Math.round(fps*1.85);const idx=sources.length?Math.floor(f/beat)%sources.length:0;const local=f%beat;const src=sources[idx]||l?.background||'';const fg=l?.foreground||inferredFg(p,k);const flash=interpolate(local,[0,2,6],[.18,.05,0],{extrapolateRight:'clamp'});const fgY=interpolate(local,[0,beat],[18,-10]);const fgScale=interpolate(local,[0,beat],[1.02,1.07]);return <AbsoluteFill style={{background:bg,overflow:'hidden'}}>{src&&<MovingMedia src={src} frame={local} dir={idx%2?1:-1}/>}<AbsoluteFill style={{background:'linear-gradient(180deg,rgba(0,0,0,.05),rgba(3,9,18,.55) 65%,rgba(3,9,18,.93))',zIndex:1}}/><Kinetic title={title} value={value} note={note}/>{fg&&<Img src={staticFile(fg)} style={{position:'absolute',left:0,right:0,bottom:0,width:'100%',height:'84%',objectFit:'contain',objectPosition:'center bottom',zIndex:3,transform:`translateY(${fgY}px) scale(${fgScale})`,filter:'drop-shadow(0 18px 28px rgba(0,0,0,.45))'}}/>}<AbsoluteFill style={{background:`rgba(255,255,255,${flash})`,zIndex:4,pointerEvents:'none'}}/><div style={{position:'absolute',top:0,left:0,height:9,width:`${interpolate(local,[0,beat],[10,100])}%`,background:`linear-gradient(90deg,${cyan},${gold})`,zIndex:5}}/><div style={{position:'absolute',right:28,top:30,zIndex:5,fontFamily:font,fontSize:12,fontWeight:900,letterSpacing:2,color:'rgba(255,255,255,.78)'}}>{src.includes('/actual-')?'ACTUAL PROPERTY':'REPRESENTATIVE VISUAL • VERIFY ON SITE'}</div></AbsoluteFill>};

const MapScene:React.FC<{p:PropertyVideoProps;title:string;value?:string;note?:string}>=({p,title,value,note})=>{const f=useCurrentFrame();const {fps}=useVideoConfig();const beat=Math.round(fps*1.8);const maps=p.maps||[];const src=maps.length?maps[Math.floor(f/beat)%maps.length]:'';const local=f%beat;const sc=interpolate(local,[0,beat],[1.03,1.16]);const pulse=1+Math.sin(f/4)*.08;return <AbsoluteFill style={{background:bg,overflow:'hidden'}}>{src&&<Img src={staticFile(src)} style={{width:'100%',height:'100%',objectFit:'cover',transform:`scale(${sc})`}}/>}<AbsoluteFill style={{background:'linear-gradient(180deg,rgba(0,0,0,.05),rgba(3,9,18,.82))'}}/><div style={{position:'absolute',left:'50%',top:'44%',width:34,height:34,margin:-17,borderRadius:999,border:`5px solid ${gold}`,transform:`scale(${pulse})`,boxShadow:`0 0 34px ${gold}`}}/><Kinetic title={title} value={value} note={note}/></AbsoluteFill>};

const CTA:React.FC<{p:PropertyVideoProps}>=({p})=>{const f=useCurrentFrame();const src=sourcesFor(p,'exterior')[0]||'';const pop=interpolate(f,[0,14],[.82,1],{extrapolateRight:'clamp'});return <AbsoluteFill style={{background:bg,overflow:'hidden'}}>{src&&<MovingMedia src={src} frame={f%75} dir={1} zoom={1.15}/>}<AbsoluteFill style={{background:'rgba(3,9,18,.68)'}}/><div style={{position:'absolute',inset:70,display:'flex',alignItems:'center',justifyContent:'center',textAlign:'center',fontFamily:font,color:cream,transform:`scale(${pop})`}}><div style={{background:'rgba(7,17,28,.72)',backdropFilter:'blur(12px)',padding:'54px 44px',borderRadius:34,border:'1px solid rgba(255,255,255,.18)',boxShadow:'0 28px 70px rgba(0,0,0,.45)'}}><div style={{fontSize:24,fontWeight:900,letterSpacing:4,color:cyan}}>BOOK A SITE VISIT</div><div style={{fontSize:76,fontWeight:1000,lineHeight:.96,marginTop:20}}>Interested in this property?</div><div style={{fontSize:48,fontWeight:1000,marginTop:36,padding:'20px 28px',borderRadius:20,background:gold,color:bg,boxShadow:`0 0 ${24+Math.sin(f/5)*8}px rgba(255,189,46,.5)`}}>{p.phone}</div><div style={{fontSize:26,marginTop:20,color:'rgba(255,255,255,.82)'}}>{p.cta}</div></div></div></AbsoluteFill>};

const visual=(p:PropertyVideoProps,s:string)=>{switch(s){case'location':return <LayeredScene p={p} scene="location" title="LOCATION" value={p.locationLabel||p.location}/>;case'price':return <LayeredScene p={p} scene="price" title="PRICE" value={p.price}/>;case'builtUp':return <LayeredScene p={p} scene="builtUp" title="BUILT-UP" value={fact(p,'built')}/>;case'facing':return <LayeredScene p={p} scene="facing" title="FACING" value={fact(p,'facing')}/>;case'road':return <MapScene p={p} title="ACCESS" value={fact(p,'road')} note="Verify access and road width during site visit"/>;case'verify':return <LayeredScene p={p} scene="verify" title="VERIFY BEFORE BUYING" note="Location • dimensions • price • documents"/>;case'approval':return <LayeredScene p={p} scene="exterior" title="APPROVAL" value={fact(p,'approval')} note="Verify documents before purchase"/>;case'cta':return <CTA p={p}/>;case'land':return <LayeredScene p={p} scene="land" title="LAND" value={fact(p,'land')}/>;default:return <LayeredScene p={p} scene="living" title={s.toUpperCase()}/>}};

export const LayeredReelV2:React.FC<PropertyVideoProps>=(p)=>{let at=0;const seq=p.sceneOrder.map((s,i)=>{const d=p.sceneDurations?.[s]||60;const from=at;at+=d;const v=voiceFor(p.voiceSegments||[],s);return <Sequence key={`${s}-${i}`} from={from} durationInFrames={d}>{visual(p,s)}{v?.src&&<Audio src={staticFile(v.src)} volume={1}/>}</Sequence>});const bgm=p.bgm||`render/${p.videoId}/bgm.wav`;return <AbsoluteFill style={{background:bg}}>{seq}<Audio src={staticFile(bgm)} volume={0.10}/></AbsoluteFill>};
