export type Fact = {label: string; value: string};
export type VisualBeat = {category: string; fromFrame: number; durationInFrames: number};
export type VoiceSegment = {scene: string; src: string; text?: string; durationInFrames?: number; visualBeats?: VisualBeat[]};
export type DirectedShot = {src: string; startFrom?: number; category?: string};
export type StyleVariant = 'cinematic' | 'fast-cut' | 'premium' | 'location-first' | 'price-first';
export type LayerMedia = {background?: string; foreground?: string; stills?: string[]};

export type PropertyVideoProps = {
  videoId: string;
  location: string;
  locationLabel: string;
  title: string;
  price: string;
  facts: Fact[];
  maps: string[];
  actualVideos: string[];
  representativeVideos: string[];
  sceneMedia: Record<string, string[]>;
  layerMedia?: Record<string, LayerMedia>;
  directorMedia?: Record<string, DirectedShot[]>;
  images: string[];
  audio: string | null;
  bgm?: string | null;
  voiceSegments: VoiceSegment[];
  sceneOrder: string[];
  sceneDurations: Record<string, number>;
  templateVariant: 'plot' | 'home';
  styleVariant?: StyleVariant;
  durationInFrames: number;
  isActualProperty: boolean;
  disclosure: string;
  brand: string;
  cta: string;
  phone: string;
};
